/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type NewsCategory = {
  _id: string;
  _type: "newsCategory";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderRank?: string;
  title?: string;
};

export type News = {
  _id: string;
  _type: "news";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderRank?: string;
  title?: string;
  slug?: Slug;
  categories?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "newsCategory";
  }>;
  mainImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  content?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          | "normal"
          | "h1"
          | "h2"
          | "h3"
          | "h4"
          | "h5"
          | "h6"
          | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        credits?: string;
        _type: "image";
        _key: string;
      }
  >;
  publishedAt?: string;
};

export type Hero = {
  _id: string;
  _type: "hero";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderRank?: string;
  title?: string;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  donateLink?: string;
  main?: boolean;
};

export type TotalRaised = {
  _id: string;
  _type: "totalRaised";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderRank?: string;
  title?: string;
  amount?: number;
};

export type Charity = {
  _id: string;
  _type: "charity";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderRank?: string;
  name?: string;
  donationUrl?: string;
  logo?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  local?: boolean;
};

export type JourneyUpdate = {
  _id: string;
  _type: "journeyUpdate";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderRank?: string;
  title?: string;
  slug?: Slug;
  mainImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  content?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          | "normal"
          | "h1"
          | "h2"
          | "h3"
          | "h4"
          | "h5"
          | "h6"
          | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        credits?: string;
        _type: "image";
        _key: string;
      }
  >;
  publishedAt?: string;
};

export type Journey = {
  _id: string;
  _type: "journey";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderRank?: string;
  title?: string;
  slug?: Slug;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    credits?: string;
    _type: "image";
  };
  description?: string;
  donationUrl?: string;
  watchUrl?: string;
  learnMoreUrl?: string;
  banner?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  charity?: {
    name?: string;
    url?: string;
  };
  speciesOrBreed?: {
    type?: "species" | "breed";
    value?: string;
  };
  location?: string;
  content?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          | "normal"
          | "h1"
          | "h2"
          | "h3"
          | "h4"
          | "h5"
          | "h6"
          | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        credits?: string;
        _type: "image";
        _key: string;
      }
  >;
  latestUpdates?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "journeyUpdate";
  }>;
  howSupportHelps?: Array<{
    icon?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    text?: string;
    _key: string;
  }>;
};

export type Event = {
  _id: string;
  _type: "event";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderRank?: string;
  title?: string;
  slug?: Slug;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  mainImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  externalLinks?: Array<{
    label?: string;
    url?: string;
    _key: string;
  }>;
  galleryImages?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  featured?: boolean;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type AllSanitySchemaTypes =
  | NewsCategory
  | News
  | Hero
  | TotalRaised
  | Charity
  | JourneyUpdate
  | Journey
  | Event
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageHotspot
  | SanityImageCrop
  | SanityFileAsset
  | SanityImageAsset
  | SanityImageMetadata
  | Geopoint
  | Slug
  | SanityAssetSourceData;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./src/sanity/lib/queries.ts
// Variable: CHARITIES_QUERY
// Query: *[_type == "charity"] | order(orderRank) {  _id,  name,  donationUrl,  local,  "logoUrl": logo.asset->url}
export type CHARITIES_QUERYResult = Array<{
  _id: string;
  name: string | null;
  donationUrl: string | null;
  local: boolean | null;
  logoUrl: string | null;
}>;
// Variable: EVENTS_QUERY
// Query: *[_type == "event"] | order(orderRank) {  _id,  _updatedAt,  title,  slug,  description,  featured,  externalLinks,  mainImage,  galleryImages[]{      asset->{        _id,        url,        metadata {          dimensions {            width,            height          }        }      }    },  "mainImageUrl": mainImage.asset->url,  "galleryImageUrls": galleryImages[].asset->url}
export type EVENTS_QUERYResult = Array<{
  _id: string;
  _updatedAt: string;
  title: string | null;
  slug: Slug | null;
  description: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  featured: boolean | null;
  externalLinks: Array<{
    label?: string;
    url?: string;
    _key: string;
  }> | null;
  mainImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  galleryImages: Array<{
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        dimensions: {
          width: number | null;
          height: number | null;
        } | null;
      } | null;
    } | null;
  }> | null;
  mainImageUrl: string | null;
  galleryImageUrls: Array<string | null> | null;
}>;
// Variable: EVENT_QUERY
// Query: *[_type == "event" && slug.current == $slug][0] {    _id,    title,    slug,    description,    featured,    externalLinks,    mainImage,    galleryImages[]{      asset->{        _id,        url,        metadata {          dimensions {            width,            height          }        }      }    },    "mainImageUrl": mainImage.asset->url,    "galleryImageUrls": galleryImages[].asset->url  }
export type EVENT_QUERYResult = {
  _id: string;
  title: string | null;
  slug: Slug | null;
  description: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  featured: boolean | null;
  externalLinks: Array<{
    label?: string;
    url?: string;
    _key: string;
  }> | null;
  mainImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  galleryImages: Array<{
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        dimensions: {
          width: number | null;
          height: number | null;
        } | null;
      } | null;
    } | null;
  }> | null;
  mainImageUrl: string | null;
  galleryImageUrls: Array<string | null> | null;
} | null;
// Variable: JOURNEYS_QUERY
// Query: *[_type == "journey"] | order(orderRank){  _id,  title,  slug,  description,  location,  donationUrl,  watchUrl,  learnMoreUrl,  "bannerUrl": banner.asset->url,  "image": {    "url": image.asset->url,    "credits": image.credits  },  content[] {      ...,      _type == "image" => {        asset->{          _id,          url,          metadata{dimensions{width, height}}        },        alt,        credits      }    },    // Charity object  charity{   _id,    name,    url  },  // Species / Breed object  speciesOrBreed{   _id,    type,    value  },  // Latest Updates  "latestUpdates": latestUpdates[]->{    _id,    title,    slug,    publishedAt,    "mainImageUrl": mainImage.asset->url,    content[] {      ...,      _type == "image" => {        asset->{          _id,          url,          metadata{dimensions{width, height}}        },        alt,        credits      }    }  },}
export type JOURNEYS_QUERYResult = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  description: string | null;
  location: string | null;
  donationUrl: string | null;
  watchUrl: string | null;
  learnMoreUrl: string | null;
  bannerUrl: string | null;
  image: {
    url: string | null;
    credits: string | null;
  };
  content: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          | "blockquote"
          | "h1"
          | "h2"
          | "h3"
          | "h4"
          | "h5"
          | "h6"
          | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset: {
          _id: string;
          url: string | null;
          metadata: {
            dimensions: {
              width: number | null;
              height: number | null;
            } | null;
          } | null;
        } | null;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        credits: string | null;
        _type: "image";
        _key: string;
        alt: null;
      }
  > | null;
  charity: {
    _id: null;
    name: string | null;
    url: string | null;
  } | null;
  speciesOrBreed: {
    _id: null;
    type: "breed" | "species" | null;
    value: string | null;
  } | null;
  latestUpdates: Array<{
    _id: string;
    title: string | null;
    slug: Slug | null;
    publishedAt: string | null;
    mainImageUrl: string | null;
    content: Array<
      | {
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?:
            | "blockquote"
            | "h1"
            | "h2"
            | "h3"
            | "h4"
            | "h5"
            | "h6"
            | "normal";
          listItem?: "bullet" | "number";
          markDefs?: Array<{
            href?: string;
            _type: "link";
            _key: string;
          }>;
          level?: number;
          _type: "block";
          _key: string;
        }
      | {
          asset: {
            _id: string;
            url: string | null;
            metadata: {
              dimensions: {
                width: number | null;
                height: number | null;
              } | null;
            } | null;
          } | null;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          credits: string | null;
          _type: "image";
          _key: string;
          alt: null;
        }
    > | null;
  }> | null;
}>;
// Variable: JOURNEY_QUERY
// Query: *[_type == "journey" && slug.current == $slug][0]{  _id,  title,  slug,  description,  location,  donationUrl,  watchUrl,  learnMoreUrl,  "bannerUrl": banner.asset->url,  "image": {    "url": image.asset->url,    "credits": image.credits  },  content[] {      ...,      _type == "image" => {        asset->{          _id,          url,          metadata{dimensions{width, height}}        },        alt,        credits      }    },    // Charity object  charity{   _id,    name,    url  },  // Species / Breed object  speciesOrBreed{   _id,    type,    value  },  // How Support Helps  howSupportHelps[]{    _id,    text,    "iconUrl": icon.asset->url  },  // Latest Updates  "latestUpdates": latestUpdates[]->{   _id,    title,    slug,    publishedAt,    "mainImageUrl": mainImage.asset->url,    content[] {      ...,      _type == "image" => {        asset->{          _id,          url,          metadata{dimensions{width, height}}        },        alt,        credits      }    }  }}
export type JOURNEY_QUERYResult = {
  _id: string;
  title: string | null;
  slug: Slug | null;
  description: string | null;
  location: string | null;
  donationUrl: string | null;
  watchUrl: string | null;
  learnMoreUrl: string | null;
  bannerUrl: string | null;
  image: {
    url: string | null;
    credits: string | null;
  };
  content: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          | "blockquote"
          | "h1"
          | "h2"
          | "h3"
          | "h4"
          | "h5"
          | "h6"
          | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset: {
          _id: string;
          url: string | null;
          metadata: {
            dimensions: {
              width: number | null;
              height: number | null;
            } | null;
          } | null;
        } | null;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        credits: string | null;
        _type: "image";
        _key: string;
        alt: null;
      }
  > | null;
  charity: {
    _id: null;
    name: string | null;
    url: string | null;
  } | null;
  speciesOrBreed: {
    _id: null;
    type: "breed" | "species" | null;
    value: string | null;
  } | null;
  howSupportHelps: Array<{
    _id: null;
    text: string | null;
    iconUrl: string | null;
  }> | null;
  latestUpdates: Array<{
    _id: string;
    title: string | null;
    slug: Slug | null;
    publishedAt: string | null;
    mainImageUrl: string | null;
    content: Array<
      | {
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?:
            | "blockquote"
            | "h1"
            | "h2"
            | "h3"
            | "h4"
            | "h5"
            | "h6"
            | "normal";
          listItem?: "bullet" | "number";
          markDefs?: Array<{
            href?: string;
            _type: "link";
            _key: string;
          }>;
          level?: number;
          _type: "block";
          _key: string;
        }
      | {
          asset: {
            _id: string;
            url: string | null;
            metadata: {
              dimensions: {
                width: number | null;
                height: number | null;
              } | null;
            } | null;
          } | null;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          credits: string | null;
          _type: "image";
          _key: string;
          alt: null;
        }
    > | null;
  }> | null;
} | null;
// Variable: JOURNEY_UPDATE_QUERY
// Query: *[_type == "journeyUpdate" && slug.current == $slug][0] {    _id,    title,    slug,    publishedAt,    "mainImageUrl": mainImage.asset->url,    content[] {      ...,      _type == "image" => {        asset->{          _id,          url,          metadata{dimensions{width, height}}        },        alt,        credits      }    }  }
export type JOURNEY_UPDATE_QUERYResult = {
  _id: string;
  title: string | null;
  slug: Slug | null;
  publishedAt: string | null;
  mainImageUrl: string | null;
  content: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          | "blockquote"
          | "h1"
          | "h2"
          | "h3"
          | "h4"
          | "h5"
          | "h6"
          | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset: {
          _id: string;
          url: string | null;
          metadata: {
            dimensions: {
              width: number | null;
              height: number | null;
            } | null;
          } | null;
        } | null;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        credits: string | null;
        _type: "image";
        _key: string;
        alt: null;
      }
  > | null;
} | null;
// Variable: TOTAL_RAISED_QUERY
// Query: *[_type == "totalRaised"] {  _id,  title,  amount}
export type TOTAL_RAISED_QUERYResult = Array<{
  _id: string;
  title: string | null;
  amount: number | null;
}>;
// Variable: HERO_CAROUSEL_QUERY
// Query: *[_type == "hero"] | order(orderRank) {  _id,  title,  description,  "imageUrl": image.asset->url,  donateLink,  main}
export type HERO_CAROUSEL_QUERYResult = Array<{
  _id: string;
  title: string | null;
  description: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  imageUrl: string | null;
  donateLink: string | null;
  main: boolean | null;
}>;
// Variable: ALL_NEWS_QUERY
// Query: *[_type == "news"] | order(publishedAt desc) {    _id,    _updatedAt,    title,    slug,    publishedAt,    "mainImageUrl": mainImage.asset->url,    categories[]->{      _id,      title    },    content[]{      ...,      _type == "image" => {        asset->{          _id,          url        },        alt      }    }  }
export type ALL_NEWS_QUERYResult = Array<{
  _id: string;
  _updatedAt: string;
  title: string | null;
  slug: Slug | null;
  publishedAt: string | null;
  mainImageUrl: string | null;
  categories: Array<{
    _id: string;
    title: string | null;
  }> | null;
  content: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          | "blockquote"
          | "h1"
          | "h2"
          | "h3"
          | "h4"
          | "h5"
          | "h6"
          | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset: {
          _id: string;
          url: string | null;
        } | null;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        credits?: string;
        _type: "image";
        _key: string;
        alt: null;
      }
  > | null;
}>;
// Variable: NEWS_QUERY
// Query: *[_type == "news" && slug.current == $slug][0] {    _id,    title,    slug,    publishedAt,    "mainImage": mainImage{      asset->{        _id,        url,        metadata{dimensions{width, height}}      },      alt    },    categories[]->{      _id,      title    },    content[] {      ...,      _type == "image" => {        asset->{          _id,          url,          metadata{dimensions{width, height}}        },        alt,        credits      }    }  }
export type NEWS_QUERYResult = {
  _id: string;
  title: string | null;
  slug: Slug | null;
  publishedAt: string | null;
  mainImage: {
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        dimensions: {
          width: number | null;
          height: number | null;
        } | null;
      } | null;
    } | null;
    alt: null;
  } | null;
  categories: Array<{
    _id: string;
    title: string | null;
  }> | null;
  content: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          | "blockquote"
          | "h1"
          | "h2"
          | "h3"
          | "h4"
          | "h5"
          | "h6"
          | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset: {
          _id: string;
          url: string | null;
          metadata: {
            dimensions: {
              width: number | null;
              height: number | null;
            } | null;
          } | null;
        } | null;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        credits: string | null;
        _type: "image";
        _key: string;
        alt: null;
      }
  > | null;
} | null;
// Variable: NEWS_CATEGORIES_QUERY
// Query: *[_type == "newsCategory"] {    _id,    title  }
export type NEWS_CATEGORIES_QUERYResult = Array<{
  _id: string;
  title: string | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type == "charity"] | order(orderRank) {\n  _id,\n  name,\n  donationUrl,\n  local,\n  "logoUrl": logo.asset->url\n}': CHARITIES_QUERYResult;
    '*[_type == "event"] | order(orderRank) {\n  _id,\n  _updatedAt,\n  title,\n  slug,\n  description,\n  featured,\n  externalLinks,\n  mainImage,\n  galleryImages[]{\n      asset->{\n        _id,\n        url,\n        metadata {\n          dimensions {\n            width,\n            height\n          }\n        }\n      }\n    },\n  "mainImageUrl": mainImage.asset->url,\n  "galleryImageUrls": galleryImages[].asset->url\n}': EVENTS_QUERYResult;
    '\n  *[_type == "event" && slug.current == $slug][0] {\n    _id,\n    title,\n    slug,\n    description,\n    featured,\n    externalLinks,\n    mainImage,\n    galleryImages[]{\n      asset->{\n        _id,\n        url,\n        metadata {\n          dimensions {\n            width,\n            height\n          }\n        }\n      }\n    },\n    "mainImageUrl": mainImage.asset->url,\n    "galleryImageUrls": galleryImages[].asset->url\n  }\n': EVENT_QUERYResult;
    '\n*[_type == "journey"] | order(orderRank){\n  _id,\n  title,\n  slug,\n  description,\n  location,\n  donationUrl,\n  watchUrl,\n  learnMoreUrl,\n  "bannerUrl": banner.asset->url,\n  "image": {\n    "url": image.asset->url,\n    "credits": image.credits\n  },\n  content[] {\n      ...,\n      _type == "image" => {\n        asset->{\n          _id,\n          url,\n          metadata{dimensions{width, height}}\n        },\n        alt,\n        credits\n      }\n    },\n  \n  // Charity object\n  charity{\n   _id,\n    name,\n    url\n  },\n\n  // Species / Breed object\n  speciesOrBreed{\n   _id,\n    type,\n    value\n  },\n\n  // Latest Updates\n  "latestUpdates": latestUpdates[]->{\n    _id,\n    title,\n    slug,\n    publishedAt,\n    "mainImageUrl": mainImage.asset->url,\n    content[] {\n      ...,\n      _type == "image" => {\n        asset->{\n          _id,\n          url,\n          metadata{dimensions{width, height}}\n        },\n        alt,\n        credits\n      }\n    }\n  },\n}\n': JOURNEYS_QUERYResult;
    '\n*[_type == "journey" && slug.current == $slug][0]{\n  _id,\n  title,\n  slug,\n  description,\n  location,\n  donationUrl,\n  watchUrl,\n  learnMoreUrl,\n  "bannerUrl": banner.asset->url,\n  "image": {\n    "url": image.asset->url,\n    "credits": image.credits\n  },\n  content[] {\n      ...,\n      _type == "image" => {\n        asset->{\n          _id,\n          url,\n          metadata{dimensions{width, height}}\n        },\n        alt,\n        credits\n      }\n    },\n  \n  // Charity object\n  charity{\n   _id,\n    name,\n    url\n  },\n\n  // Species / Breed object\n  speciesOrBreed{\n   _id,\n    type,\n    value\n  },\n\n  // How Support Helps\n  howSupportHelps[]{\n    _id,\n    text,\n    "iconUrl": icon.asset->url\n  },\n\n  // Latest Updates\n  "latestUpdates": latestUpdates[]->{\n   _id,\n    title,\n    slug,\n    publishedAt,\n    "mainImageUrl": mainImage.asset->url,\n    content[] {\n      ...,\n      _type == "image" => {\n        asset->{\n          _id,\n          url,\n          metadata{dimensions{width, height}}\n        },\n        alt,\n        credits\n      }\n    }\n  }\n}\n': JOURNEY_QUERYResult;
    '\n  *[_type == "journeyUpdate" && slug.current == $slug][0] {\n    _id,\n    title,\n    slug,\n    publishedAt,\n    "mainImageUrl": mainImage.asset->url,\n    content[] {\n      ...,\n      _type == "image" => {\n        asset->{\n          _id,\n          url,\n          metadata{dimensions{width, height}}\n        },\n        alt,\n        credits\n      }\n    }\n  }\n': JOURNEY_UPDATE_QUERYResult;
    '*[_type == "totalRaised"] {\n  _id,\n  title,\n  amount\n}': TOTAL_RAISED_QUERYResult;
    '*[_type == "hero"] | order(orderRank) {\n  _id,\n  title,\n  description,\n  "imageUrl": image.asset->url,\n  donateLink,\n  main\n}': HERO_CAROUSEL_QUERYResult;
    '\n  *[_type == "news"] | order(publishedAt desc) {\n    _id,\n    _updatedAt,\n    title,\n    slug,\n    publishedAt,\n    "mainImageUrl": mainImage.asset->url,\n    categories[]->{\n      _id,\n      title\n    },\n    content[]{\n      ...,\n      _type == "image" => {\n        asset->{\n          _id,\n          url\n        },\n        alt\n      }\n    }\n  }\n': ALL_NEWS_QUERYResult;
    '\n  *[_type == "news" && slug.current == $slug][0] {\n    _id,\n    title,\n    slug,\n    publishedAt,\n    "mainImage": mainImage{\n      asset->{\n        _id,\n        url,\n        metadata{dimensions{width, height}}\n      },\n      alt\n    },\n    categories[]->{\n      _id,\n      title\n    },\n    content[] {\n      ...,\n      _type == "image" => {\n        asset->{\n          _id,\n          url,\n          metadata{dimensions{width, height}}\n        },\n        alt,\n        credits\n      }\n    }\n  }\n': NEWS_QUERYResult;
    '\n  *[_type == "newsCategory"] {\n    _id,\n    title\n  }\n': NEWS_CATEGORIES_QUERYResult;
  }
}
